# Generated by Django 3.1.5 on 2021-01-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['last_name'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Recursos Humanos'},
        ),
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades de Empleado'},
        ),
        migrations.RenameField(
            model_name='habilidades',
            old_name='habilidades',
            new_name='habilidad',
        ),
    ]
